spring:
  application:
    name: spring-security-template
  profiles:
    active: dev

cors:
  allowed-origins: "http://localhost:5173,http://localhost:4200"
  allowed-methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
  allowed-headers: "*"

security:
  jwt:
    provider: jjwt
    issuer: security-template
    algorithm: RSA


